CUDA_VISIBLE_DEVICES: "0"
model: "lingshu-medical-mllm/Lingshu-32B"
served_model_name: "Lingshu-32B"
port: 8000
trust_remote_code: true
max_model_len: 12000
gpu_memory_utilization: 0.9
max_num_seqs: 8
seed: 42
