CUDA_VISIBLE_DEVICES: "0"
model: "/home/kbia984/00_nesi_projects/uoa04670_nobackup/kbia984/models/Neurlps2026-SFT/DentalCaries/slms/gemma-4-E4B-it/merged"
served_model_name: "gemma-4-E4B-it-SFT"
port: 9005
trust_remote_code: true
max_model_len: 16384
limit_mm_per_prompt: '{"image": 16}'
gpu_memory_utilization: 0.90
max_num_seqs: 16
seed: 42
