CUDA_VISIBLE_DEVICES: "0"
model: "<MODEL_ROOT>/DR/llms/Lingshu-32B/merged"
served_model_name: "Lingshu-32B-SFT"
port: 8000
trust_remote_code: true
max_model_len: 12000
gpu_memory_utilization: 0.9
max_num_seqs: 8
seed: 42
